
services:
  payment-service:
    image: paymentimage:latest
    container_name: paymentcontainer
    ports:
      - "8081:8070"  # Host:Container
    depends_on:
      - eureka
      - gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservices-network

  eureka:
    build: ./eureka
    image: zeinebdgfs/eureka:latest
    container_name: eureka-container
    ports:
      - "8020:8761"
    networks:
      - microservices-network
  gateway:
    build: ./gateway
    image: zeinebdgfs/gateway:latest
    container_name: gateway-container
    ports:
      - "8013:8020"
    depends_on:
      - eureka
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservices-network

  reservation-service:
    build: ./Microservices/Reservation
    image: zeinebdgfs/reservation:latest
    container_name: reservation-container
    ports:
      - "8050:8082"
    depends_on:
      - eureka
      - gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservices-network
  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:24.0.1
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin_farouk
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080



networks:
    microservices-network:
     driver: bridge